# Site settings
title: Jakob Lange - Portfolio
email: webjakob@gmail.com
name: Jakob Lange
firstname: Jakob
description: > # this means to ignore newlines until "baseurl:"
  Jakob Langes portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jakobbl.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  jakobbl

# Build settings
markdown: kramdown
permalink: /projects/:title
timezone: Europe/Copenhagen

#Post variables
thumbnailpath: /assets/project-thumbnails/
heropath: /assets/hero/
imgpath: assets/images

defaults:
  -
    scope:
      type: "posts"
    values:
      thumbnail: placeholder.png
      heropos: center center
